### ISSUE TITLE
Seeding bug

### ISSUE THREAD

**Issue by alisherbek-rakhimov** [yangez/btree-js#3]
When i seed with 0 random numbers, numbers are not added (I enter a number and click "add" button, but nothing happens).

**Comment by CheyenneForbes** [comment]
btree-js doesn't seem to like "0" 🤣 because when I try to insert "0" it says "Please enter a valid integer."

**Comment by CheyenneForbes** [comment]
for the time, you can open the developer console then go to sources and edit the seed function in btree.js and replace it with your code (using `this.insert(my_value, true);` to insert your desired numbers)

![image](https://user-images.githubusercontent.com/8251976/53715262-3d029b00-3e1f-11e9-9856-09f37dad0bf5.png)

if any of your numbers is a "0" you will need to make the following changes in `btree-node.js` (I made a pull request)

![image](https://user-images.githubusercontent.com/8251976/53715685-99b28580-3e20-11e9-8464-0cdbe76034fc.png)

**Comment by voxlol** [comment]
i believe fixed in https://github.com/yangez/btree-js/pull/4
